// Generated by CoffeeScript 1.8.0
var fs = require('fs');
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

module.exports = {
  webpackDevPort: webpackDevPort,
  plugins:[
    new webpack.DefinePlugin({
      __DEBUG__:true
    }),
  ],
  externals:{
    'pixi':'PIXI',
    'PIXI':'PIXI'
  },
  resolve: {
    extensions: ['', '.js']
  },
  entry: {
    main:'./src/index.js'
  },
  output: {
    path: path.resolve(__dirname, './public/dist'),
    publicPath: "/public/dist",
    filename: 'main.js'
  },
  module: {
    loaders: [
      {
        test: /\.ejs$/,
        loader: 'ejs-loader?variable=data'
      }
    ]
  },
  devtool: 'source-map'
};

//# sourceMappingURL=webpack.config.js.map
